import { useState } from "react";
import { useApp, CredentialType, AppCredential, CredentialScope } from "@/contexts/AppContext";
import {
  Dialog, DialogContent, DialogHeader, DialogTitle, DialogDescription, DialogFooter,
} from "@/components/ui/dialog";
import { Button } from "@/components/ui/button";
import { Input } from "@/components/ui/input";
import { Label } from "@/components/ui/label";
import { Badge } from "@/components/ui/badge";
import { Checkbox } from "@/components/ui/checkbox";
import { Switch } from "@/components/ui/switch";
import {
  Select, SelectContent, SelectItem, SelectTrigger, SelectValue,
} from "@/components/ui/select";
import { Textarea } from "@/components/ui/textarea";
import { Key, Globe, Server, Copy, Check, AlertTriangle, ArrowRight, ArrowLeft } from "lucide-react";
import { useToast } from "@/hooks/use-toast";
import { cn } from "@/lib/utils";

interface CreateCredentialModalProps {
  open: boolean;
  onOpenChange: (open: boolean) => void;
  appId: string;
}

const typeOptions = [
  { value: "api_key" as CredentialType, label: "API Key", description: "Bearer token for server-to-server API calls", icon: Key },
  { value: "oauth2" as CredentialType, label: "OAuth 2.0", description: "Client credentials or authorization code flow", icon: Globe },
  { value: "service_account" as CredentialType, label: "Service Account", description: "Public key authentication for automated systems", icon: Server },
];

const PRODUCT_PERMISSIONS: Record<string, string[]> = {
  sms: ["sms.send", "sms.status", "sms.list"],
  rcs: ["rcs.send", "rcs.status", "rcs.rich_card", "rcs.carousel"],
  whatsapp: ["wa.template", "wa.send", "wa.status", "wa.interactive"],
  webhooks: ["webhook.subscribe", "webhook.manage"],
};

export function CreateCredentialModal({ open, onOpenChange, appId }: CreateCredentialModalProps) {
  const { apps, createCredential } = useApp();
  const app = apps.find((a) => a.id === appId);
  const { toast } = useToast();

  const [step, setStep] = useState(1);
  const [type, setType] = useState<CredentialType>("api_key");
  const [name, setName] = useState("");
  const [isPermanent, setIsPermanent] = useState(true);
  const [expiryDate, setExpiryDate] = useState("");
  const [selectedScopes, setSelectedScopes] = useState<CredentialScope[]>([]);

  // OAuth specific
  const [grantTypes, setGrantTypes] = useState<("authorization_code" | "client_credentials")[]>(["client_credentials"]);
  const [redirectUris, setRedirectUris] = useState("");
  const [thirdPartyAppName, setThirdPartyAppName] = useState("");

  // Service account specific
  const [publicKey, setPublicKey] = useState("");

  // Result
  const [createdCredential, setCreatedCredential] = useState<AppCredential | null>(null);
  const [copied, setCopied] = useState<string | null>(null);

  if (!app) return null;

  const enabledProducts = app.products.filter((p) => p.status !== "disabled");

  const handleToggleScope = (productId: string, permission: string) => {
    setSelectedScopes((prev) => {
      const existing = prev.find((s) => s.product === productId);
      if (existing) {
        const hasPermission = existing.permissions.includes(permission);
        if (hasPermission) {
          const newPerms = existing.permissions.filter((p) => p !== permission);
          if (newPerms.length === 0) return prev.filter((s) => s.product !== productId);
          return prev.map((s) => s.product === productId ? { ...s, permissions: newPerms } : s);
        } else {
          return prev.map((s) => s.product === productId ? { ...s, permissions: [...s.permissions, permission] } : s);
        }
      }
      return [...prev, { product: productId, permissions: [permission] }];
    });
  };

  const isScopeSelected = (productId: string, permission: string) => {
    return selectedScopes.some((s) => s.product === productId && s.permissions.includes(permission));
  };

  const handleCreate = () => {
    const base: Omit<AppCredential, "id" | "createdAt"> = {
      name: name || `${typeOptions.find((t) => t.value === type)?.label} - ${new Date().toLocaleDateString()}`,
      type,
      status: "active",
      createdBy: app.email,
      lastUsedAt: null,
      expiresAt: isPermanent ? null : expiryDate || null,
      scopes: selectedScopes,
    };

    if (type === "api_key") {
      // apiKey will be generated by context
      base.apiKey = `helo_live_${Math.random().toString(36).substring(2, 26)}`;
    } else if (type === "oauth2") {
      base.clientId = `helo_client_${Math.random().toString(36).substring(2, 15)}`;
      base.clientSecret = `helo_secret_${Math.random().toString(36).substring(2, 15)}${Math.random().toString(36).substring(2, 15)}`;
      base.grantTypes = grantTypes;
      base.redirectUris = redirectUris ? redirectUris.split("\n").filter(Boolean) : [];
      base.thirdPartyAppName = thirdPartyAppName || undefined;
    } else if (type === "service_account") {
      base.publicKey = publicKey;
      base.keyFormat = "RSA/PEM";
    }

    const result = createCredential(appId, base);
    setCreatedCredential({ ...base, id: result.id, createdAt: result.createdAt } as AppCredential);
    setStep(4);
    toast({ title: "Credential created", description: `${base.name} has been created successfully.` });
  };

  const handleCopy = (text: string, label: string) => {
    navigator.clipboard.writeText(text);
    setCopied(label);
    setTimeout(() => setCopied(null), 2000);
  };

  const handleClose = () => {
    onOpenChange(false);
    setTimeout(() => {
      setStep(1);
      setType("api_key");
      setName("");
      setIsPermanent(true);
      setExpiryDate("");
      setSelectedScopes([]);
      setGrantTypes(["client_credentials"]);
      setRedirectUris("");
      setThirdPartyAppName("");
      setPublicKey("");
      setCreatedCredential(null);
      setCopied(null);
    }, 200);
  };

  const canProceedStep2 = name.trim().length > 0;
  const canProceedStep3 = type === "service_account" ? publicKey.trim().length > 0 : true;

  return (
    <Dialog open={open} onOpenChange={handleClose}>
      <DialogContent className="sm:max-w-lg">
        <DialogHeader>
          <DialogTitle>
            {step === 4 ? "Credential Created" : `Create Credential — Step ${step} of 3`}
          </DialogTitle>
          <DialogDescription>
            {step === 1 && "Select the type of credential to create"}
            {step === 2 && "Configure credential details and scope"}
            {step === 3 && `Configure ${typeOptions.find((t) => t.value === type)?.label} settings`}
            {step === 4 && "Store these credentials securely — they won't be shown again"}
          </DialogDescription>
        </DialogHeader>

        {/* Step 1: Select Type */}
        {step === 1 && (
          <div className="space-y-3 py-2">
            {typeOptions.map((opt) => {
              const Icon = opt.icon;
              return (
                <button
                  key={opt.value}
                  onClick={() => setType(opt.value)}
                  className={cn(
                    "w-full flex items-center gap-4 p-4 rounded-lg border text-left transition-colors",
                    type === opt.value
                      ? "border-primary bg-primary/5"
                      : "border-border hover:border-foreground/20"
                  )}
                >
                  <div className="p-2 rounded-lg bg-muted">
                    <Icon className="h-5 w-5" />
                  </div>
                  <div>
                    <p className="text-sm font-medium">{opt.label}</p>
                    <p className="text-xs text-muted-foreground">{opt.description}</p>
                  </div>
                </button>
              );
            })}
          </div>
        )}

        {/* Step 2: Name, Expiry, Scopes */}
        {step === 2 && (
          <div className="space-y-4 py-2">
            <div className="space-y-2">
              <Label>Credential Name <span className="text-destructive">*</span></Label>
              <Input value={name} onChange={(e) => setName(e.target.value)} placeholder="e.g. Production API Key" />
            </div>
            <div className="space-y-2">
              <Label>Expiry</Label>
              <div className="flex items-center gap-3">
                <Switch checked={isPermanent} onCheckedChange={setIsPermanent} />
                <span className="text-sm text-muted-foreground">{isPermanent ? "Permanent (no expiry)" : "Set expiry date"}</span>
              </div>
              {!isPermanent && (
                <Input type="date" value={expiryDate} onChange={(e) => setExpiryDate(e.target.value)} />
              )}
            </div>
            <div className="space-y-2">
              <Label>API Scopes</Label>
              <p className="text-xs text-muted-foreground">Select products and permissions this credential can access</p>
              <div className="space-y-3 max-h-48 overflow-y-auto">
                {enabledProducts.filter((p) => p.id !== "webhooks").map((product) => {
                  const perms = PRODUCT_PERMISSIONS[product.id] || [];
                  return (
                    <div key={product.id} className="rounded-md border p-3 space-y-2">
                      <p className="text-sm font-medium">{product.name}</p>
                      <div className="grid grid-cols-2 gap-2">
                        {perms.map((perm) => (
                          <label key={perm} className="flex items-center gap-2 text-xs cursor-pointer">
                            <Checkbox
                              checked={isScopeSelected(product.id, perm)}
                              onCheckedChange={() => handleToggleScope(product.id, perm)}
                            />
                            <code className="font-mono">{perm}</code>
                          </label>
                        ))}
                      </div>
                    </div>
                  );
                })}
                {enabledProducts.filter((p) => p.id !== "webhooks").length === 0 && (
                  <p className="text-sm text-muted-foreground py-2">No products enabled. Enable products first to assign scopes.</p>
                )}
              </div>
            </div>
          </div>
        )}

        {/* Step 3: Type-specific */}
        {step === 3 && (
          <div className="space-y-4 py-2">
            {type === "api_key" && (
              <div className="rounded-md border border-border bg-muted/30 p-4 space-y-2">
                <div className="flex items-center gap-2 text-sm">
                  <Key className="h-4 w-4" />
                  <span className="font-medium">API Key Generation</span>
                </div>
                <p className="text-xs text-muted-foreground">
                  A secure API key will be generated automatically. It will be displayed once after creation — store it securely.
                </p>
              </div>
            )}
            {type === "oauth2" && (
              <>
                <div className="space-y-2">
                  <Label>Grant Types</Label>
                  <div className="space-y-2">
                    {(["client_credentials", "authorization_code"] as const).map((gt) => (
                      <label key={gt} className="flex items-center gap-2 text-sm cursor-pointer">
                        <Checkbox
                          checked={grantTypes.includes(gt)}
                          onCheckedChange={(checked) => {
                            setGrantTypes((prev) =>
                              checked ? [...prev, gt] : prev.filter((g) => g !== gt)
                            );
                          }}
                        />
                        {gt === "client_credentials" ? "Client Credentials" : "Authorization Code"}
                      </label>
                    ))}
                  </div>
                </div>
                {grantTypes.includes("authorization_code") && (
                  <div className="space-y-2">
                    <Label>Redirect URIs</Label>
                    <Textarea
                      value={redirectUris}
                      onChange={(e) => setRedirectUris(e.target.value)}
                      placeholder="https://your-app.com/callback\nhttps://localhost:3000/callback"
                      className="font-mono text-xs resize-none min-h-[72px]"
                    />
                    <p className="text-xs text-muted-foreground">One URI per line</p>
                  </div>
                )}
                <div className="space-y-2">
                  <Label>Third-Party App Name <span className="text-xs text-muted-foreground font-normal">(optional)</span></Label>
                  <Input value={thirdPartyAppName} onChange={(e) => setThirdPartyAppName(e.target.value)} placeholder="e.g. CRM Integration" />
                </div>
              </>
            )}
            {type === "service_account" && (
              <div className="space-y-2">
                <Label>Public Key (RSA/PEM) <span className="text-destructive">*</span></Label>
                <Textarea
                  value={publicKey}
                  onChange={(e) => setPublicKey(e.target.value)}
                  placeholder="-----BEGIN PUBLIC KEY-----\n...\n-----END PUBLIC KEY-----"
                  className="font-mono text-xs resize-none min-h-[120px]"
                />
                <p className="text-xs text-muted-foreground">Paste your RSA public key in PEM format</p>
              </div>
            )}
          </div>
        )}

        {/* Step 4: Created - Show Secrets */}
        {step === 4 && createdCredential && (
          <div className="space-y-4 py-2">
            <div className="flex items-start gap-3 p-3 rounded-md bg-warning/10 border border-warning/20">
              <AlertTriangle className="h-4 w-4 text-warning shrink-0 mt-0.5" />
              <p className="text-xs text-warning">Store these credentials securely. They will not be shown again.</p>
            </div>

            {createdCredential.type === "api_key" && createdCredential.apiKey && (
              <SecretRow label="API Key" value={createdCredential.apiKey} copied={copied} onCopy={handleCopy} />
            )}
            {createdCredential.type === "oauth2" && (
              <>
                {createdCredential.clientId && (
                  <SecretRow label="Client ID" value={createdCredential.clientId} copied={copied} onCopy={handleCopy} />
                )}
                {createdCredential.clientSecret && (
                  <SecretRow label="Client Secret" value={createdCredential.clientSecret} copied={copied} onCopy={handleCopy} />
                )}
              </>
            )}
            {createdCredential.type === "service_account" && (
              <div className="rounded-md border p-3 space-y-1">
                <p className="text-xs font-medium">Service Account</p>
                <p className="text-xs text-muted-foreground">Public key has been registered. Use the corresponding private key for authentication.</p>
              </div>
            )}

            <div className="rounded-md border p-3 space-y-1">
              <p className="text-xs font-medium">Credential ID</p>
              <code className="text-xs font-mono text-muted-foreground">{createdCredential.id}</code>
            </div>
          </div>
        )}

        <DialogFooter>
          {step < 4 && (
            <div className="flex w-full justify-between">
              <Button variant="outline" onClick={() => step === 1 ? handleClose() : setStep(step - 1)}>
                {step === 1 ? "Cancel" : <><ArrowLeft className="h-4 w-4 mr-1" /> Back</>}
              </Button>
              {step < 3 ? (
                <Button onClick={() => setStep(step + 1)} disabled={step === 2 && !canProceedStep2}>
                  Next <ArrowRight className="h-4 w-4 ml-1" />
                </Button>
              ) : (
                <Button onClick={handleCreate} disabled={!canProceedStep3}>
                  Create Credential
                </Button>
              )}
            </div>
          )}
          {step === 4 && (
            <Button onClick={handleClose} className="w-full">Done</Button>
          )}
        </DialogFooter>
      </DialogContent>
    </Dialog>
  );
}

function SecretRow({ label, value, copied, onCopy }: { label: string; value: string; copied: string | null; onCopy: (text: string, label: string) => void }) {
  return (
    <div className="rounded-md border p-3 space-y-1.5">
      <p className="text-xs font-medium">{label}</p>
      <div className="flex items-center gap-2">
        <code className="flex-1 text-xs font-mono bg-muted px-3 py-2 rounded break-all">{value}</code>
        <Button variant="outline" size="icon" className="h-9 w-9 shrink-0" onClick={() => onCopy(value, label)}>
          {copied === label ? <Check className="h-3.5 w-3.5 text-success" /> : <Copy className="h-3.5 w-3.5" />}
        </Button>
      </div>
    </div>
  );
}
